project:
  type: book
  output-dir: docs

number-sections: true
# top-level-division: part
toc-depth: 3
number-depth: 4
bibliography: reference.bib
csl: "ims.csl"
 
crossref:
  labels: arabic        # (default is arabic)
  subref-labels: roman i # (default is alpha a)
 
execute:
  freeze: auto

knitr:
  opts_chunk:
    # comment: "#>"
    collapse: true

jupyter: stats

# filters:
#   - pseudocode

# pseudocode:
#   caption-prefix: "Algorithm"
#   reference-prefix: "Algorithm"
#   caption-number: true

format:
  bookup-html:
        toc: true
        toc-depth: 3
        css: styles/blocks.css
  # html:
  #   theme: cosmo
  #   code-block-bg: true
  #   code-block-border-left: true #"#31BAE9"
  #   # code-line-numbers: true
  #   highlight-style: atom-one
  #   page-layout: article
 
book:
  title: "Regression 26 Spring"
  author: "Xinli Xiao"
  date: last-modified
  chapters: 
    - index.qmd
    - part: "Review"
      chapters:
      - contents/1/basics.qmd
      - contents/1/prob.qmd
      - contents/1/inferences.qmd      
      # - contents/0/statsmodels.qmd
    - part: "Simple Linear regression"
      chapters: 
      - contents/2/intro.qmd
      - contents/2/slr.qmd
      - contents/2/rcode.qmd
      - contents/2/project1.qmd
    - part: "Multiple Linear regression"
      chapters:
      - contents/3/mlr.qmd
      # - contents/3/anova.qmd
      # - contents/3/categorical.qmd
      # - contents/3/rcode2.qmd
      # - contents/3/project2.qmd
    # - part: "Building models"
    #   chapters:
    #   - contents/4/intro.qmd
      # - contents/4/misc.qmd
  appendices:
    - contents/app/data.qmd
    - contents/app/r.qmd
  sidebar:
    style: "docked"
    # pinned: true
    # align: center
    # border: true
    search: true
    collapse-level: 1
    # alignment: "center"
  # navbar: 
  #   background: primary
  #   search: true
  #   left: 
  #     - text: "Home"
  #       menu: 
  #       - contents/index.qmd
  page-navigation: true
  bread-crumbs: false
 
   